settings:
  warning-enabled: true
  warning-timer: 20
  broadcast:
    - ""
    - "&c&lFACTIONS &8&l▶ &7The &9CrystalZone &7has begun regenerating outside of &9/spawn&7."
    - ""

paste-location:
  world: "spawn"
  x: -24
  y: 85
  z: -8